# Generated by Django 5.2.4 on 2025-11-01 17:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General Nutrition'), ('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('healthy_eating', 'Healthy Eating'), ('sports_nutrition', 'Sports Nutrition'), ('diet_plans', 'Diet Plans'), ('recipes', 'Recipes')], default='general', max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
            ],
            options={
                'verbose_name': 'Nutrition Article',
                'verbose_name_plural': 'Nutrition Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', max_length=2)),
                ('model_used', models.CharField(default='nutrition', help_text='AI model used for this conversation', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise 3-5 days/week)'), ('active', 'Very active (hard exercise 6-7 days/week)'), ('very_active', 'Extremely active (very hard exercise & physical job)')], max_length=20)),
                ('health_goal', models.CharField(choices=[('weight_loss', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('muscle_gain', 'Build Muscle'), ('improve_health', 'Improve Overall Health')], max_length=20)),
                ('bmi', models.FloatField()),
                ('bmi_category', models.CharField(max_length=50)),
                ('bmr', models.FloatField(help_text='Basal Metabolic Rate')),
                ('maintenance_calories', models.IntegerField(help_text='Daily maintenance calories')),
                ('target_calories', models.IntegerField(help_text='Recommended daily calorie target')),
                ('dietary_preferences', models.TextField(blank=True)),
                ('food_allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Assessment',
                'verbose_name_plural': 'Health Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='MealSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(help_text='Protein in grams')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams')),
                ('fats', models.FloatField(help_text='Fats in grams')),
                ('fiber', models.FloatField(default=0, help_text='Fiber in grams')),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField(blank=True)),
                ('cooking_time', models.IntegerField(default=15, help_text='Cooking time in minutes')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_low_carb', models.BooleanField(default=False)),
                ('is_high_protein', models.BooleanField(default=False)),
                ('health_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_suggestions', to='core.healthassessment')),
            ],
            options={
                'verbose_name': 'Meal Suggestion',
                'verbose_name_plural': 'Meal Suggestions',
                'ordering': ['meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Lightly active (light exercise 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise 3-5 days/week)'), ('active', 'Very active (hard exercise 6-7 days/week)'), ('very_active', 'Extremely active (very hard exercise & physical job)')], default='sedentary', max_length=20)),
                ('diet_preference', models.CharField(choices=[('none', 'No specific diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean'), ('low_carb', 'Low Carb'), ('gluten_free', 'Gluten Free'), ('dairy_free', 'Dairy Free')], default='none', max_length=20)),
                ('dietary_preferences', models.TextField(blank=True, help_text='Any dietary restrictions or preferences')),
                ('food_allergies', models.TextField(blank=True, help_text='List any food allergies')),
                ('health_goals', models.TextField(blank=True, help_text='Your health and nutrition goals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('target_calories', models.IntegerField(blank=True, null=True)),
                ('water_intake_goal', models.FloatField(default=2.0, help_text='Daily water intake goal in liters')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='FavoriteMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_meals', to=settings.AUTH_USER_MODEL)),
                ('meal_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mealsuggestion')),
            ],
            options={
                'verbose_name': 'Favorite Meal',
                'verbose_name_plural': 'Favorite Meals',
                'unique_together': {('user', 'meal_suggestion')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used in this message', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='core_messag_convers_53e97e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('calories_consumed', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('water_intake', models.FloatField(blank=True, help_text='Water intake in liters', null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('workout_minutes', models.IntegerField(blank=True, null=True)),
                ('mood_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progress Tracking',
                'verbose_name_plural': 'Progress Tracking',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
