# Generated by Django 5.2.4 on 2025-11-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='healthassessment',
            new_name='core_health_user_id_c71d4a_idx',
            old_name='core_health_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='healthassessment',
            new_name='core_health_bmi_cat_07a93d_idx',
            old_name='core_health_bmi_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='progresstracking',
            new_name='core_progre_user_id_5a9ddb_idx',
            old_name='core_progress_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='core_userpr_user_id_830b32_idx',
            old_name='core_userpr_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='core_userpr_activit_99aa9d_idx',
            old_name='core_userpr_activity_idx',
        ),
    ]
