# Generated by Django 5.2.4 on 2025-11-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_health_user_date_idx_core_health_user_id_c71d4a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assessments', models.IntegerField(default=0)),
                ('total_chat_messages', models.IntegerField(default=0)),
                ('total_favorite_meals', models.IntegerField(default=0)),
                ('last_assessment_date', models.DateTimeField(blank=True, null=True)),
                ('last_chat_date', models.DateTimeField(blank=True, null=True)),
                ('profile_completion_percentage', models.IntegerField(default=0, help_text='0-100 percentage')),
                ('total_usage_count', models.IntegerField(default=0)),
                ('days_active', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_active_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('health_assessment', 'Health Assessment'), ('chat', 'Chat Assistant'), ('view_assessment', 'View Assessment'), ('profile_update', 'Profile Update'), ('view_meals', 'View Meal Suggestions'), ('favorite_meal', 'Favorite Meal'), ('progress_tracking', 'Progress Tracking'), ('ocr', 'OCR Feature'), ('article_view', 'Article View'), ('login', 'Login'), ('logout', 'Logout')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client information')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Tracking',
                'verbose_name_plural': 'Usage Tracking',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_usaget_user_id_5fc525_idx'), models.Index(fields=['feature', '-timestamp'], name='core_usaget_feature_d8c7c7_idx')],
            },
        ),
    ]
