# Generated by Django 5.2.4 on 2025-11-23 12:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_tokens_processing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-pinned', '-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user last read this conversation', null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin conversation to top of sidebar'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default=core.models._generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', max_length=2),
        ),
    ]
