# Generated by Django 5.2.4 on 2025-11-29 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('confirmation', 'Email Confirmation'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('notification', 'Notification'), ('other', 'Other')], default='other', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message_preview', models.TextField(help_text='First 500 chars of message', max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='core_emaill_user_id_682a6e_idx'), models.Index(fields=['email_type'], name='core_emaill_email_t_7fa3e2_idx'), models.Index(fields=['is_sent'], name='core_emaill_is_sent_ae40a2_idx')],
            },
        ),
    ]
